#@METADATA os=rocky-10
#===============================================================================
# rocky-SCH.init
# Additional initialization for Rocky SCH (Storage Cluster Host) profile
#===============================================================================

# Create ZFS pool on free disk
n_zpool_create_on_free_disk

# Install OpenSVC packages
n_install_opensvc_packages

# Start OpenSVC daemon
n_osvc_start

# Initialize OpenSVC cluster membership
n_initialise_opensvc_cluster

