#@METADATA os=alpine-3 type=TCH profile=KVM
#===============================================================================
# alpine-KVM.init  
# Additional initialization for Alpine KVM profile
#===============================================================================
# Install KVM packages and setup
n_install_kvm

n_install_opensvc_packages
n_osvc_start
n_initialise_opensvc_cluster



# Start libvirt service
n_start_libvirt


