__guard_source || return

## HPS Functions


#:name: _ini_get_agent_nodename
#:group: opensvc
#:synopsis: Extract [agent] nodename from an opensvc.conf
#:usage: _ini_get_agent_nodename /etc/opensvc/opensvc.conf
_ini_get_agent_nodename() {
  local f="${1:?usage: _ini_get_agent_nodename <file>}"
  awk -F= '
    /^\[agent\]/ { agent_section=1; next }
    agent_section && $1 ~ /^[ \t]*nodename[ \t]*$/ {
      v=$2; sub(/^[ \t]*/,"",v); sub(/[ \t]*$/,"",v); print v; exit
    }
    /^\[/ { agent_section=0 }
  ' "$f"
}

#:name: _osvc_kv_set
#:group: opensvc
#:synopsis: Set an OpenSVC v3 key using om config set key=value
#:usage: _osvc_kv_set key value
_osvc_kv_set() {
  local k="${1:?key}" v="${2:?value}"
  om config set "${k}=${v}"
}




#:name: _osvc_kv_set
#:group: opensvc
#:synopsis: Set an OpenSVC v3 key using om config set --kw key=value
#:usage: _osvc_kv_set key value
_osvc_kv_set() {
  local k="${1:?key}" v="${2:?value}"
  om config set --kw "${k}=${v}"
}

#:name: generate_opensvc_conf
#:group: opensvc
#:synopsis: Emit an OpenSVC v3 opensvc.conf to STDOUT (does NOT write to disk).
#:usage: generate_opensvc_conf [<ips_role>]
#:description:
#  Origin identity is $(hps_origin_tag). IPS is container-resident and not in host_config:
#    - TYPE forced to IPS
#    - nodename forced to "ips"
#  Non-IPS: nodename from host_config "<origin>" HOSTNAME; fallback to sanitized origin.
#  Cluster-scope options read from cluster_config.
generate_opensvc_conf() {
  local ips_role="${1:-}"

  local origin; origin="$(hps_origin_tag)"

  # Host-scoped
  local osvc_nodename osvc_type osvc_tags
  osvc_type="$(host_config "$origin" get TYPE 2>/dev/null || true)"

  if [[ "${osvc_type^^}" == "IPS" || -z "$osvc_type" && "${origin,,}" == "ips" ]]; then
    osvc_type="IPS"
    osvc_nodename="ips"   # stable in-container name
  else
    osvc_nodename="$(host_config "$origin" get HOSTNAME 2>/dev/null || true)"
    [[ -z "$osvc_nodename" ]] && osvc_nodename="$(echo "$origin" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-')"
  fi

  # IPS role: CLI > host_config > cluster_config > default
  [[ -z "$ips_role" ]] && ips_role="$(host_config "$origin" get IPS_ROLE 2>/dev/null || true)"
  [[ -z "$ips_role" ]] && ips_role="$(cluster_config get OSVC_IPS_ROLE 2>/dev/null || true)"
  [[ -z "$ips_role" ]] && ips_role="provisioning"

  case "${osvc_type^^}" in
    IPS)     osvc_tags="ips ${ips_role,,}" ;;  # controller/dispatcher only
    SCH)     osvc_tags="storage zfs" ;;
    TCH|CCH) osvc_tags="compute" ;;
    "")      osvc_tags="" ;;
    *)       osvc_tags="$(echo "$osvc_type" | tr '[:upper:]' '[:lower:]')" ;;
  esac

  # Cluster-scoped
  local osvc_log_level osvc_listener_port osvc_web_ui osvc_web_port osvc_hb_interval osvc_hb_timeout
  local osvc_templates_url osvc_packages_url
  osvc_log_level="$(cluster_config get OSVC_LOG_LEVEL 2>/dev/null || echo info)"
  osvc_listener_port="$(cluster_config get OSVC_LISTENER_PORT 2>/dev/null || echo 7024)"
  osvc_web_ui="$(cluster_config get OSVC_WEB_UI 2>/dev/null || echo yes)"
  osvc_web_port="$(cluster_config get OSVC_WEB_PORT 2>/dev/null || echo 7023)"
  osvc_hb_interval="$(cluster_config get OSVC_HB_INTERVAL 2>/dev/null || echo 5)"
  osvc_hb_timeout="$(cluster_config get OSVC_HB_TIMEOUT 2>/dev/null || echo 15)"
  osvc_templates_url="$(cluster_config get OSVC_TEMPLATES_URL 2>/dev/null || echo)"
  osvc_packages_url="$(cluster_config get OSVC_PACKAGES_URL 2>/dev/null || echo)"

  # Static paths
  local conf_dir="/etc/opensvc"
  local var_dir="/var/lib/opensvc"
  local log_file="/var/log/opensvc/agent.log"
  local auth_key_file="/etc/opensvc/agent.key"

  cat <<EOF
# OpenSVC v3 Agent Node Configuration (generated by HPS)

[agent]
nodename = ${osvc_nodename}
tags = ${osvc_tags}
conf_dir = ${conf_dir}
var_dir = ${var_dir}
log_file = ${log_file}
log_level = ${osvc_log_level}
listener_port = ${osvc_listener_port}
web_ui = ${osvc_web_ui}
web_ui_port = ${osvc_web_port}
hb_interval = ${osvc_hb_interval}
hb_timeout  = ${osvc_hb_timeout}
auth_key_file = ${auth_key_file}

[repo]
templates_url = ${osvc_templates_url}
packages_url  = ${osvc_packages_url}

[stats]
enable = yes
push_interval = 60
EOF
install_opensvc_foreground_wrapper
}



#:name: osvc_apply_identity_from_hps
#:group: opensvc
#:synopsis: Enforce IPS node.name and set cluster.name from HPS CLUSTER_NAME (OpenSVC v3).
#:usage: osvc_apply_identity_from_hps
#:description:
#  - If /etc/opensvc/opensvc.conf nodename == "ips", set node.name=ips in v3 KV.
#  - Always set cluster.name=<CLUSTER_NAME> from HPS cluster_config.
osvc_apply_identity_from_hps() {
  local conf="/etc/opensvc/opensvc.conf"
  [[ -r "$conf" ]] || { hps_log error "[opensvc] missing $conf"; return 1; }

  local nn; nn="$(_ini_get_agent_nodename "$conf")"
  if [[ -z "$nn" ]]; then
    hps_log error "[opensvc] nodename not found in $conf [agent]"; return 1
  fi

  if [[ "$nn" == "ips" ]]; then
    _osvc_kv_set "node.name" "$nn" || hps_log warn "[opensvc] failed to set node.name=${nn}"
  fi

  local cn; cn="$(cluster_config get CLUSTER_NAME 2>/dev/null || true)"
  if [[ -n "$cn" ]]; then
    _osvc_kv_set "cluster.name" "$cn" || hps_log warn "[opensvc] failed to set cluster.name=${cn}"
  else
    hps_log warn "[opensvc] CLUSTER_NAME not found; cluster.name not set"
  fi
}




#:name: install_opensvc_foreground_wrapper
#:group: opensvc
#:synopsis: Install /usr/local/sbin/opensvc-foreground to run the OpenSVC v3 daemon in foreground with clean logs.
#:usage: install_opensvc_foreground_wrapper
#:description:
#  Writes an exec wrapper that:
#    - ensures runtime dirs (/run/opensvc, /var/log/opensvc, /var/lib/opensvc, ${HPS_LOG_DIR}) exist
#    - verifies /etc/opensvc/agent.key exists and is non-empty (fails fast otherwise)
#    - execs 'om daemon run' (OpenSVC v3) in the foreground
#    - funnels agent stdout/stderr to ${HPS_LOG_DIR}/opensvc.{out,err}.log
#    - filters the noisy "zerolog … journal/socket" lines from stderr (no journald in container)
#  Notes:
#    - Idempotent: only rewrites the file if content changed.
#    - No supervisorctl calls; service control is handled elsewhere.
install_opensvc_foreground_wrapper() {
  local target="/usr/local/sbin/opensvc-foreground"
  local logdir="${HPS_LOG_DIR:-/srv/hps-system/log}"

  mkdir -p "$(dirname "$target")" "$logdir"

  # Desired wrapper content
  local tmp
  tmp="$(mktemp "${target}.XXXXXX")" || { hps_log error "[opensvc] mktemp failed"; return 1; }
  cat >"$tmp" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# Use HPS log dir if provided, fallback otherwise.
LOGDIR="${HPS_LOG_DIR:-/srv/hps-system/log}"

# Preflight: required directories (ok if already exist)
mkdir -p /run/opensvc /var/log/opensvc /var/lib/opensvc "${LOGDIR}"

# Preflight: agent key must exist and be non-empty
if [[ ! -s /etc/opensvc/agent.key ]]; then
  echo "[opensvc] FATAL: /etc/opensvc/agent.key missing or empty" >&2
  exit 2
fi

# Run the v3 daemon in foreground so a supervisor can manage it if desired.
# Filter the noisy journald error lines from stderr; keep everything else.
# Agent also writes its own file log as configured in /etc/opensvc/opensvc.conf.
exec /usr/bin/om daemon run \
  1>>"${LOGDIR}/opensvc.out.log" \
  2> >(stdbuf -o0 awk '!/zerolog: could not write event: write unixgram .*journal\/socket/' >> "${LOGDIR}/opensvc.err.log")
EOF

  chmod 0755 "$tmp"

  # Idempotent install: only replace if content differs
  if [[ -f "$target" ]]; then
    if cmp -s "$tmp" "$target"; then
      rm -f "$tmp"
      hps_log info "[opensvc] Wrapper already current: ${target}"
      return 0
    fi
  fi

  mv -f "$tmp" "$target"
  hps_log info "[opensvc] Installed wrapper: ${target}"
}








